### ISSUE TITLE
在代码里面没有发现上传图片的api

### ISSUE THREAD

**Issue by mrjesen** [git268/SchoolDaysDemo#4]
在代码里面没有发现上传图片的api 
$apis['put-photo']

**Comment by git268** [comment]
是不是请假或者有其他任务顶了。输出一下查寝页面$datas。
如print_r($datas);

**Comment by mrjesen** [comment]
array(5) { ["dayInMonth"]=> NULL ["codeRcvdTasks"]=> array(0) { } ["signedTasks"]=> array(0) { } ["unSignedTasks"]=> array(0) { } ["leaveTasks"]=> array(0) { } }

**Comment by mrjesen** [comment]
array(5) { ["dayInMonth"]=> NULL ["codeRcvdTasks"]=> array(0) { } ["signedTasks"]=> array(0) { } ["unSignedTasks"]=> array(0) { } ["leaveTasks"]=> array(0) { } }

**Comment by mrjesen** [comment]
是我搞错了，这个是签到不是查寝。。

**Comment by git268** [comment]
...

**Comment by mrjesen** [comment]
太尴尬了

**Comment by mrjesen** [comment]
..

**Comment by mrjesen** [comment]
n个月前我抓的api是`/wec-counselor-sign-apps/stu/oss/getUploadPolicy` 不知道还能不能用。

**Comment by git268** [comment]
加个QQ2206822527，老得挂梯回复
